networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: vector_database
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - ALLOW_RESET=TRUE
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net
    restart: always
  database:
    image: mysql:lts
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: wmmks65802
      MYSQL_USER: mi2s
      MYSQL_PASSWORD: wmmks65802
    restart: always
    ports:
      - 3306:3306
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: wmmks65802
    ports:
      - 8505:80
    networks:
      - net
    restart: always
    depends_on:
      - database
  rag_app:
    build: .
    container_name: rag_app
    ports:
      - 8501:8501
    volumes:
      - ./:/app
    networks:
      - net
    restart: always
    depends_on:
      - chromadb
      - database
    command: streamlit run rag_engine.py
  graph_rag:
    image: neo4j:5.8.0-enterprise
    container_name: graph_rag
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./graphData/data:/data
      - ./graphData/logs:/logs
      - ./graphData/import:/var/lib/neo4j/import
      - ./graphData/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enables=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file__neo4j__config=true
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_allowlist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_server_memory_heap_initial__size=4G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4J_AUTH=neo4j/wmmks65802
    restart: always
    networks:
      - net
